# @host = localhost:8080
@host = 172.16.0.13:8741

GET http://{{host}}/health HTTP/1.1

###

GET http://{{host}}/optimal-hours
    ?max_hours=4
    &threshold=0.1

###

# Test with max_hours=0 to disable scheduling
GET http://{{host}}/optimal-hours
    ?max_hours=0
    &threshold=0.1