@host = localhost:8080

GET http://{{host}}/health HTTP/1.1

###

# Test consecutive windows with ranges
GET http://{{host}}/optimal-hours
    ?max_hours=3
    &threshold=1
    &consecutive=true

GET http://{{host}}/optimal-hours
    ?max_hours=4
    &threshold=0.1

###

# Test with max_hours=0 to disable scheduling
GET http://{{host}}/optimal-hours
    ?max_hours=0
    &threshold=0.1
